apiVersion: v1
kind: Service
metadata:
 name: node-port-tp
 namespace: production 
spec:
 type: NodePort
 selector:
   app: web
   
 ports:
 - nodePort: 30008
   protocol: TCP
   port: 8080
   targetPort: 8080
